language: php

php:
  - '7.1'
  - '7.2'

before_install:
  - composer global require hirak/prestissimo

install:
  - composer install --no-progress --profile

script:
  - vendor/bin/codecept run --coverage --coverage-xml

after_success:
  - php bin/ocular.phar code-coverage:upload --format=php-clover tests/_output/coverage.xml